enum PieceEnum {
  POTION_TIMER_5 = "5",
  POTION_TIMER_4 = "4",
  POTION_TIMER_3 = "3",
  POTION_TIMER_2 = "2",
  POTION_TIMER_1 = "1",
  BLAST = "҉",
  WALL = "☼",
  TREASURE_BOX = "#",
  TREASURE_BOX_OPENING = "H",
  GHOST = "&",
  GHOST_DEAD = "x",
  POTION_BLAST_RADIUS_INCREASE = "+",
  POTION_COUNT_INCREASE = "c",
  POTION_REMOTE_CONTROL = "r",
  POTION_IMMUNE = "i",
  POISON_THROWER = "T",
  POTION_EXPLODER = "A",
  NONE = " ",
  HERO = "☺",
  HERO_POTION = "☻",
  HERO_DEAD = "Ѡ",
  OTHER_HERO = "♥",
  OTHER_HERO_POTION = "♠",
  OTHER_HERO_DEAD = "♣",
  ENEMY_HERO = "ö",
  ENEMY_HERO_POTION = "Ö",
  ENEMY_HERO_DEAD = "ø",
}

export { PieceEnum };
